const position_list_array: {[key:number]: string[]} = {
    2:[
        'big_blind',
        'small_blind',
    ],
    3:[
        'big_blind',
        'small_blind',
        'under_the_gun',
    ],
    4:[
        'big_blind',
        'small_blind',
        'under_the_gun',
        'cut_off',
    ],
    5:[
        'big_blind',
        'small_blind',
        'under_the_gun',
        'cut_off',
        'button',
    ],
    6:[
        'big_blind',
        'small_blind',
        'under_the_gun',
        'middle_position',
        'cut_off',
        'button',
    ],
    7:[
        'big_blind',
        'small_blind',
        'under_the_gun',
        'middle_position',
        'middle_position_plus_1',
        'cut_off',
        'button',
    ],
    8:[
        'big_blind',
        'small_blind',
        'under_the_gun',
        'middle_position',
        'middle_position_plus_1',
        'middle_position_plus_2',
        'cut_off',
        'button',
    ],
    9:[
        'big_blind',
        'small_blind',
        'under_the_gun',
        'middle_position',
        'middle_position_plus_1',
        'middle_position_plus_2',
        'middle_position_plus_3',
        'cut_off',
        'button',
    ],
}

export default () => {
    const copy = {}
    return Object.assign(copy, position_list_array)
}